slynch8/10x

PythonScripts/CompileDbCmd/CompileDbCmd.py
PythonScripts/CompileDbCmd/README.md

This is a script that parses `compile_commands.json` files and can do single file compilations in the project from that information.
It is useful for workspaces without msvc solutions, especially when opening folders with arbitrary build processes like `ninja`

Initial CompileDbCmd script

---

PythonScripts/RemedyBG/README.md
PythonScripts/RemedyBG/RemedyBG.py

- Renamed functions
- Can launch new remedy session if it's not running
- Syncs 10x breakpoints at start
Improved RemedyBG integration, there are still some things missing from having a better connection:
- To start a Remedy session, I'm passing the workspace executable `GetWorkspaceExePath()`. But we need more information to initialize a correct debugging session, like `GetWorkspaceExeArgs()` and `GetWorkspaceExeCwd()` and probably `GetWorkspaceExeEnvVars()` if that even exists.
- As we discussed before, having a `AddProjectDebugFunction` to override msvc debugging would help, so after `RemedyBGStart` command, we could issue the command and run the remedy session instead of msvc.

More RemedyBG improvements

---

PythonScripts/RemedyBG/RemedyBG.py

the previous version only worked if you had the setting defined to exactly `true`

make RemedyBG.Hook setting more robust

---

PythonScripts/RemedyBG/README.md
PythonScripts/RemedyBG/RemedyBG_Updater.py

A script to automatically update RemedyBG.  Requires a few settings to be able to scan for new updates and to initiate the download from itch.io.
The new settings that will be needed:
```
RemedyBG_Updater.PortalToken:		""
RemedyBG_Updater.ItchLoginCookie:	""
RemedyBG_Updater.ItchLoginToken:	""
RemedyBG_Updater.StartPage: 1
RemedyBG_Updater.PagesToScan:	 2
RemedyBG_Updater.MaxVersionHistory: 1
RemedyBG_Updater.UpdateOnBoot: true
```
These settings should default to empty strings:
- RemedyBG_Updater.PortalToken
- RemedyBG_Updater.ItchLoginCookie
- RemedyBG_Updater.ItchLoginToken
These settings should default to these values:
- RemedyBG_Updater.StartPage: 1
- RemedyBG_Updater.PagesToScan: 2
- RemedyBG_Updater.MaxVersionHistory: 1
- RemedyBG_Updater.UpdateOnBoot: false

RemedyBG Updater First Release

---

PythonScripts/Vim/Vim.py

Pass through F-Keys and mouse buttons when in command mode. Allows user to build solution with F7 when in command mode for example.

Fix editor shortcuts when in command mode.

---

PythonScripts/Vim/Vim.py

- Added `i_` and `a_` text-object motions
- word (`w`)
- Blocks (`{}`, `()`, `<>`, `[]`)
- Quotes (`""`, `''`,  ``` `` ```)
- eg. `ci{` will change the block on the same line as your cursor, or the enclosing one.
- Better line delete (`dd`)
- Better paste and clipboard error handling
- Added `AddVisualModeSelection`
- Status text reflects current mode

Vim: Added Text-object motions, better line delete and paste, status text shows mode

---

PythonScripts/Vim/Vim.py

Features:
- Implement `{` and `}` motions to Visual mode
- Add `Y` (alias for `yy`)
- Add `p`aste to Visual mode
Bugfixes:
- Fixed `ci"` deleting empty strings
- Fixed quote text-object motion only working for double quoted strings
- Fixed one-off error when a selection is added to the current one
- Fixed same-line text-object motions when there are two blocks
- Fixed AtEndOfFile logic, which caused FindEnclosingBlockEndPos to loop forever
- `vi_` and `va_` no longer adds to your selection when using block motions
- `{` and `}` will jump to the start or end of a file if a non-empty line can't be found

Vim: Motion additions, improvements and bugfixes

---

PythonScripts/Vim/Vim.py

- Fixed same-line text-object motion being prioritized when there was non-whitespace characters preceding it
- Fixed `ci_` inserting a line above the entire block when the block start had whitespace

Vim: Fix same-line text-object motions, fix `ci_` inserting new lines in edge cases

---

PythonScripts/Vim/Vim.py

- Fixed `yi"` crashing
- Fixed `da"` and `di"` crashing
- Fixed `P` regression (fixes #1641)
- Renamed `SelectQuote` to `SelectAroundQuote` for consistency with its block text-object equivalent

Vim: Fix quote text-object motions and `P` command

---

PythonScripts/RemedyBG/README.md

Documentation :
```
python3 -m pip install --target="C:\Program Files\PureDevSoftware\10x" requests
python3 -m pip install --target="C:\Program Files\PureDevSoftware\10x" BeautifulSoup4
```
The target is `C:\Program Files\PureDevSoftware\10x` but the documentation indicates :
```
Adding Packages
To add packages to the 10x python installation copy the package file or folder to the site-packages folder in the 10x install folder and restart 10x.
C:\Program Files\PureDevSoftware\10x\Lib\site-packages\
```
So i replaced `C:\Program Files\PureDevSoftware\10x` by `C:\Program Files\PureDevSoftware\10x\Lib\site-packages\`.

RemedyBG: typo on 10x's installation directory

---

PythonScripts/Vim/Vim.py

fixes:
- `A` and others didn't work correctly with `.`
- subsequent macro recordings would append
cleanups:
- playback buffer doesn't navigate ignoring key presses: just pipes everything through
feature:
- auto enable "ReverseFindSelection"

fixes, cleanups, and feature

---

PythonScripts/Vim/Vim.py

- unhilighting is currently done by just explicitly setting the cursor to where it already is. seems to work fine, but an exposed API might be more future proof
- there is a bug in the editor (not the vim script) where the last line of a multiline indent/unindent is doubled, so this hack fix just unhilights and executes the reverse
- stubbed keybinding overrides assumes the setting "VimOverrideKeybinding" and the editor api `N10X.Editor.HasKeybinding(key, shift, control alt)`, but is commented out. will update/rename if those get added.
question: with `N10X.Editor.GetSetting("x")`, is there such a concept as a default value? like if it's not present from the setting file, will it just return false?

fixes involving unhilighting, space unhilighting, hacked fix around multiline indent, stubbed vim keybinding overrides

---

PythonScripts/RemedyBG/RemedyBG.py

Starts RemedyBG with the executable instead of blank instance. Debug command seems to be working as expected afterwards.

Sets executable path for RemedyBG on initialize

---

PythonScripts/Vim/Vim.py

fixed bug introduced a while ago where `Fx` would correctly go backwards, but subsequent `;`s would un-reverse the direction and go forward again

fixed continuous ; direction

---

PythonScripts/CMakeIntegration/CMakeIntegration.py

Allows users to set cmake variables over commandline by modifying build and rebuild commands, small patch to the search algorithm that was bugged for projects using CMakeSettings.json.

Use workspace build and rebuild commands to pass cmake variables and fix case insensitive search

---

PythonScripts/SortLines/SortLines.py

added an optional argument to SortLines() and SortSelectedLines() that ignores case sensitivity by default.

Ignore case when sorting by default

---

PythonScripts/Vim/Vim.py

Exception variable is named ex, not err
As a result of this issue, my 10x editor became effectively stuck in INSERT mode but with a block cursor. No Escape or Control C sequence could go into NORMAL mode.
I don't have a good idea of what caused the issue or error, except that I think an auto-complete window of some kind had popped up at the time.
10x error output:
```
[python] Traceback (most recent call last):
[python]   File "C:/Users/gavin/AppData/Roaming/10x/PythonScripts/Vim.py", line 317, in AddNewlineToClipboard
[python]     win32clipboard.OpenClipboard()
[python] pywintypes.error: (5, 'OpenClipboard', 'Access is denied.')
[python] 
During handling of the above exception, another exception occurred:
[python] Traceback (most recent call last):
[python]   File …
```

Fix Vim.py clipboard error handling

---

PythonScripts/Vim/Vim.py

When losing file focus, only go back into command mode if we're not suspended

Fix suspend mode being disabled on focus loss

---

ColorSchemes/SolarizedLight.10x_settings

Hi,
I wrote a port of the [Solarized Light](https://ethanschoonover.com/solarized/) color scheme using the preexisting color scheme "Light" as a base.
Although I followed the official colors, I did make some personal choices for things that weren't mentioned in their website, like the member/non member functions and variables.
I've been using it full time for about a week and I think it'll be nice to have it included as part of the official color schemes, since a lot of other editors/IDEs include it (or some variation of it) by default.
Here's a small preview:
Thanks.

Add a port of the Solarized Light color scheme

---

PythonScripts/RemedyBG/RemedyBG.py

Added 10x CommandLineArgSelector support with immediate changes to RemedyBG session. Needs RemedyBG v0.4.0.4 and higher.

Add CommandLineArgSelector support for RemedyBG

---

PythonScripts/ClangFormat/ClangFormat.py

Seems faster in this environment. With shell=True, the shell window no longer pops up and everything completes in ms rather than seconds.

Speedup for ClangFormat. Set shell=True when invoking from Python.

---

PythonScripts/Vim/Vim.py

New commandline mode that uses the status text bar to emulate vim commandline-mode in a more natural vim way, rather than using 10x command panel. \
This is for commands that start with `:` and searching with `/`. However searching is currently unsupported as we're awaiting some new 10x commands to support it. 
Experimental and open for feedback. It's disabled by default and can be enabled by setting VimEnableCommandlineMode: true in settings and restarting 10x.
Known missing features:
* Add support for command history
* Support searching 
* Support substitution
Demonstration:

New commandline mode WIP

---

PythonScripts/Vim/Vim.py
PythonScripts/Vim/VimUser.py

VimUser is designed to not be updated often by maintainers but to be modified locally. This is to reduce the effort of having to merge Vim.py for user overrides. 
See example usage in VimUser.py. You can either handle keys and commands yourself or specify for them to be sent to 10x instead of the Vim script. 
Smaller Changes:
* Added Vim callback registration behind `if __name__ == "__main__"` to void multiple registrations when imported by VimUser.py.
* Fixed g_HandlingKey typo
* Removed g_VimOverrideKeybindings as it doesn't do anything and was confusing.

Added VimUser.py for user-overridden key handlers

---

PythonScripts/Vim/Vim.py

When deleting characters in the status bar when searching it would not actually update the find text.

Fixed vim search not updating when deleting characters

---

PythonScripts/SignatureCreator/SignatureCreator.py

Prior to this commit, if you have ```void Prototype();``` in the header and then exercise the ```Define()``` function, you would end up with ```void Classname::Prototype();{}``` in your cpp file. This change prevents that.

Remove semicolon from header prototype

---

PythonScripts/Vim/Vim.py

EnterSuspendedMode was accidentally broken in a previous commit.

Fix suspended mode

---

PythonScripts/Vim/Vim.py

""H"/"M"/"L" and "zt"/"zz"/"zb" added to visual mode

---

PythonScripts/RemedyBG/RemedyBG.py

Workspaces (I think - untested) and .sln files can have spaces in their names and still be valid - this just ensures that the Remedy server has the correct named pipe when starting

Added missing " to args when starting up Remedy
