PythonScripts/ClangFormat/ClangFormat.py, PythonScripts/ClangFormat/README.md
Adds support for setting values and FormatSelection functionality
Default FormatFile.py can be replaced with this plugin
=> Improved ClangFormat plugin, supports FormatSelection as well

PythonScripts/OverrideSettings/OverrideSettings.py, PythonScripts/OverrideSettings/README.md
Settings can be overrided with an extra settings file placed in the workspace directory
=> Added OverrideSettings script

PythonScripts/RemedyBG/RemedyBG.py
`Update` function was very buggy and just annoying, I removed it for now to come up with better checks later
=> Remedy bg fix

PythonScripts/Vim/Vim.py
Adds support for dw, dW and cW
=> Adding CutToEndOfWord & Line

PythonScripts/RemedyBG/RemedyBG.py
Invalidates RemedyBG session if either active project/config/platform is changed
=> Added config, active, platform build change

PythonScripts/Vim/Vim.py
Fix word navigation w,e,b in visual mode
Fix delete(d), cut(x), replace(c) in visual mode
Fix yank in visual mode
=> Visual mode fixes

PythonScripts/RemedyBG/RemedyBG.py
`GET_BREAKPOINT_LOCATIONS` only returns resolved breakpoints, meaning that adding new breakpoints isn't bi-directional since breakpoints added by the user in RemedyBG while not actively debugging will not be retrieved by the editor, meaning that they get out of sync.
Instead call `GET_BREAKPOINT`, which returns breakpoint locations whether they're resolved or not.
---
Current behavior:
https://user-images.githubusercontent.com/21160174/213872496-93eeb1fe-0366-4851-8ef7-2bef312b1f33.mp4
New behavior:
https://user-images.githubusercontent.com/21160174/213872504-4ea0f353-0d2e-4ce7-95bc-ba37af7238d4.mp4
=> RemedyBG: Retrieve unresolved breakpoints

PythonScripts/RemedyBG/RemedyBG.py
For septag's comment here: https://github.com/slynch8/10x/pull/1378#pullrequestreview-1266142064
=> RemedyBG: Increment version

PythonScripts/Vim/Vim.py
The entire system was somewhat reworked to better accommodate the vim features. A lot of things like movement have been restricted to better match vim, moving around is no longer really handled by 10x but instead by the python script, and regex is used (abused?) to handle the vim grammar. I've only been using this for a couple of days, so it's not entirely battle-tested yet, but I will add more features/bug fixes after this preliminary improvement.
=> Expanded Vim Functionality

PythonScripts/Vim/Vim.py
Add missing move to word end (e) command in visual mode.
=> Visual Mode: Fix move to word end (e)

PythonScripts/Vim/Vim.py
fixed 'r' in place, 'r''R' undo blocks, swapped 'Pane Mode' into a bool rather than a full mode, removed extranneous ;s
=> small fixes

PythonScripts/Vim/Vim.py
I made these fixes a long time ago but forgot to upstream, sorry !
=> Fixing bugs in vim_sneak emulation

PythonScripts/RemedyBG/RemedyBG.py
As a newcommer this was really confusing to get to work so this is a few extra lines documenting the process.
=> Update comments on RemedyBG.py

PythonScripts/Vim/Vim.py
=> More Vim.py commands

PythonScripts/TortoiseSVN/TortoiseSVN.py
Hello,
I have added some very basic commands to be able to show log/show diff/blame the current file with the help of TortoiseProc. Follow the same commands as https://tortoisesvn.net/visualstudio.html integration.
=> Add TortoiseSVN.py

PythonScripts/Vim/Vim.py
=>  Add `de` command

PythonScripts/Vim/Vim.py
Previously you could disable and enable vim using `:de` and `:ev:` but this meant you couldn't type `:` to fix this copy the standard of VsVim keyboard shortcut instead.
This change still requires the Vim script to be enabled, it does not disable/enable that.
=> Disable/Enable Vim with ctrl+shift+f12

PythonScripts/FormatOnSave/FormatOnSave.py, PythonScripts/FormatOnSave/README.md
Adds a plugin that saves/formats files when they loose focus.
With this plugin you sometimes get a notification that the file is in usage.
Its not a big deal, but can be  annoying.
=> Add Format\Save on focus lost plugin

PythonScripts/Vim/Vim.py
Fixed J and gJ
Added ~
Fixed { and }
=> Vim.py edits

ColorSchemes/Abyss.10x_settings
=> Add Abyss colour scheme

PythonScripts/SortLines/SortLines.py
I find this to be useful when sorting headers in .cpp/.h files
=> Update SortLines.py to include SortSelectedLines method

PythonScripts/README.md, PythonScripts/SignatureCreator/README.md, PythonScripts/SignatureCreator/SignatureCreator.py
Remember asking about this feature on the discord server. Someone mentioned I should do a pull request whenever I do make that script, so that's what I did!
This addition will add a Define python function that will turn definitions like this on the .h file
void DoThing(int A, float B);
into this
void UNBBarksSubsystem::DoThing(int A, float B)
{
}
That's bout it
=> Added a Signature Creator python script

PythonScripts/CMakeIntegration/CMakeIntegration.py, PythonScripts/README.md
Detects and builds cmake projects using cmake commandline.
Writes 10x workspaces for project folders with CMakeLists.txt files.
=> Add CMakeIntegration.py

PythonScripts/CMakeIntegration/CMakeIntegration.py
Will need people to test the integration to be sure, but hopefully this handles version 4 includes correctly.
=> Add processing of CMakeUserPresets.json and includes

PythonScripts/CMakeIntegration/CMakeIntegration.py
Finds vcvarsall.bat and uses it to set environment variables that cmake more than likely will want. Solves a case where cmake cannot find standard libraries. Reorganizes some variables to be global that aren't modified often so that fewer subprocesses are launched to complete a build.
=> Make use of vcvarsall.bat to set environment variables

ColorSchemes/Kanagawa.10x_settings
Feel free to modify the first section of the theme if you would like.
Preview:
=> Add Kanagawa Theme

PythonScripts/SortLines/SortLines.py
pulled down the script on a new PC and realized it was missing the import
=> Added missing import

PythonScripts/AddInclude/AddInclude.py
- Use GetSymbolDefinitionFilename API
- Place cursor back onto the symbol after the command runs
- Check for top-level comments when inserting includes
- Ensure paths use "/" path separators as backslashes are UB
=> Improve AddInclude.py script with new GetSymbolDefinitionFilename API

PythonScripts/SmartSpace/SmartSpace.py
Good morning Stewart,
we had talked about the visual case where the next line is empty but there is a count of 2 and it returns GetCursorPos the last y position, the fix handles it better.
Jens
=> Handle visual edge case better

PythonScripts/Vim/Vim.py
Allows keyboard shortcut of find in files
=> pass through ctrl+shit+f

PythonScripts/Vim/Vim.py
Missing exit from visual mode with ctrl+C
=> Exit visual mode with ctrl+c

PythonScripts/Vim/Vim.py
Updated so that commandline mode can set a status bar text on executing a command. 
This is so you can see that it did actually run it. 
Most changes are just renaming g_Error to g_CommandlineResultText so it's more generic.
=> Write 'saved file' to status bar after running :w or :wa

PythonScripts/Vim/Vim.py
Check for x != None instead of x != 0
=> Fix reverse search when character is at start of line

PythonScripts/Vim/Vim.py
This adds a new setting called VimExitInsertModeCharSequence which you can set to your favoured keystroke such as jj/jk etc. Just add it to the settings file.
=> Add keystroke functionality to exit insert mode

PythonScripts/Vim/Vim.py
Still some corner case that is not handled, but for the most part visual block for copy cut and delete are working.
Not sure what is the correct behavior for moving vertically since I mapped gj and gk to j and k, right now the current vim.py behavior for moving vertically will be different with when on Visual Block Mode. To make it the same, just commented out  
```python    
if g_Mode != Mode.VISUAL_BLOCK:
x = min(GetLineLength(y) - max_offset, x)
```
Not yet tested for all corner case, so can be disabled with g_VisualBlockModeEnabled, default to True
=> CTRL-V Visual block implementation

PythonScripts/Vim/Vim.py
Shift+i shift+a are required to enter insert mode from visual mode
=> Fix visual mode i commands, e.g. viw

PythonScripts/Vim/README.md, PythonScripts/Vim/Vim.py
Commands and searching is now done in the status panel which is more vim like. These can be disabled using VimUse10xFindPanel and VimUse10xCommandPanel
Added vim readme so explain vim customization and vim settings
=> Vim search and command line use status panel by default

PythonScripts/Vim/Vim.py
smart case searching turns on case-sensitve search if one upper case letter is present.
Also reverse search with `?` is now supported.
=> Added smart case and reverse searching

PythonScripts/Vim/README.md, PythonScripts/Vim/Vim.py
Search and command history is now remembered for current session
Group commandline mode data into CommandlineModeContext struct
Added new Vim setting VimCommandlineFilteredHistory which controls whether the history is filtered based on what has already been typed, same as nvim.
=> Added history to commandline mode

PythonScripts/SignatureCreator/SignatureCreator.py, PythonScripts/SignatureCreator/Utilities.py, PythonScripts/SignatureCreator/UtilitiesTests.py
List of functionality:
* By-default define in Source file, DefineInCurrentFile to define in current file
* Fixed generation when default parameters present e.x. void Foo(int a = 2, FVector b = (3.f, 2.f) -> void Foo(int a, FVector b)
* Fixed generation doesn't start if selected anything besides FunctionDeclaration or MemberFunctionDeclaration
* Fixed generation when complex return type like const int* const
* Fixed override, final specifiers weren't removed
* Fixed Define in return type aren't omitted e.x. ENGINE_API void Foo() -> void Foo()
* Fixed GoTo definition after generation or when definition exists
Misc:
* Added SourceCodeLine class to easily do string manipulation while keeping CursorPos info for 10X api calls
* Added basic tests for SourceCodeLine
Known limitation:
* No …
=> Improved version of SignatureCreator.py

PythonScripts/Vim/Vim.py
these commands would delete too far back - selection was backwards
=> Fix db/dB/cb/cB deleting too much

PythonScripts/Vim/Vim.py
Commands: `<C-w>n <C-w>v <C-w>q <C-w>c`
Note: I think we need a new command for closing panes, need to check.
=> Added missing window commands for splitting and closing 

PythonScripts/Vim/Vim.py
=> @simpsongsd I think I got it right this time

PythonScripts/Vim/Vim.py
Add support for detecting AltGr and fixing the pass through so { can be accessed on German keyboards
Also added str repr to Key class
=> AltGr support, iW and aW commands

PythonScripts/RemedyBG/RemedyBG.py
- Improved event receiver loop, so it gets all pending messages in one go instead of per-frame. Much better response time.
- Fixes and improvements to the first start of the app. For some reason, we don't received TargetStarted event when executable runs for the first time. This change fixes that.
- Added RDBG_Break command
=> RemedyBG  0.12.4

PythonScripts/RemedyBG/RemedyBG.py
0.13.0
- BREAKING: RemedyBG.Path and RemedyBG.Hook options has been removed. With the newer 10x editor versions, you only need to set DebuggerPath setting to remedybg.exe path and it will automatically hook itself to the project.
- Added version checking
=> Remedy bg v0.13.0

PythonScripts/AddInclude/AddInclude.py, PythonScripts/GenerateVSProjectFiles/GenerateVSProjectFiles.py, PythonScripts/GenerateVSProjectFiles/README.md, PythonScripts/GenerateVSProjectFiles/UE_GenerateVSProjectFiles.py
Created a script that allows the 10x user to generate the Visual Studi…o solution and project files that back the Visual Studio Workspace in 10x
=> Gen VS Solution from inside 10x

PythonScripts/AddInclude/AddInclude.py
I found that after turning off intellisense generation, header files were being inserted into the VS project files in a way that the AddInclude.py script would not find, resulting in absolute paths to header files being inserted when using the script.
Also, making sure that if an include is being generated to always place it above any .generated.h includes, as doing otherwise will cause a compile time build break when dealing with UE projects.
=> Ensure include files are found regardless of intellisense build setting
